apiVersion: extensions/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kafka-consumer
        version: v.0.0.1
    spec:
      containers:
      - name: kafka-consumer
        image: docker.io/jsenon/kafka-consumer:latest
        env:
        - name: MY_KAFKABOOTSTRAP
          value: ""
        - name: MY_TOPIC
          value: ""
        - name: MY_GROUPID
          value: "001"
        imagePullPolicy: Always
        ports:
        - containerPort: 9010
