apiVersion: extensions/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: kafka-consumer-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-consumer-dev
        version: v.0.0.1
    spec:
      containers:
      - name: kafka-consumer-dev
        image: docker.io/jsenon/kafka-consumer:develop
        env:
        - name: MY_KAFKABOOTSTRAP
          value: "100.69.163.174:9092"
        - name: MY_TOPIC
          value: "datahub"
        - name: MY_GROUPID
          value: "consumergroup2"
        imagePullPolicy: Always
